config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  get 'tags/create'

  get 'tags/update'

  get 'tags/new'

  get 'tags/edit'

  get 'tags/destroy'

  get 'tags/show'

  get 'tags/index'

  get 'works/create'

  get 'works/update'

  get 'works/new'

  get 'works/edit'

  get 'works/destroy'

  get 'works/show'

  get 'works/index'

  root 'home#index'

  resources :tags
  resources :works

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :works
end

app/models/work.rb
class Work < ApplicationRecord
	belongs_to :tag
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@tags = Tag.all
  	@works = Work.all
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def create
    @tag = Tag.new(tag_params)
    if @tag.save
      flash[:notice] = "New Tag created"
      redirect_to tags_index_path
    else
      flash[:alert] = "Error occured"
      render 'new'
    end
  end

  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      flash[:notice] = "Updated"
      redirect_to tags_index_path
    else
      flash[:alert] = "Error occured"
      render 'edit'
    end
  end

  def new
    @tag = Tag.new
    @works = Work.all
    @tags = Tag.all
  end

  def edit
    @tag = Tag.find(params[:id])
    @tags = Tag.all
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    flash[:notice] = "Deleted"
    redirect_to tags_index_path
  end

  def show
    @tag = Tag.find(params[:id])
    @tags = Tag.all
  end

  def index
    @tags = Tag.all
  end

  private
  def tag_params
    params.require(:tag).permit(:name)
  end

end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def create
    @tags = Tag.all
    @work = Work.new(work_params)
    if @work.save
      flash[:notice] = "Saved"
      redirect_to root_path
    else
      flash[:notice] = "error occured!"
      render 'new'
    end
  end

  def update
    @work = Work.find(params[:id])
    @work.update(work_params)
    redirect_to works_index_path
  end

  def new
    @work = Work.new
    @tags = Tag.all
  end

  def edit
    @tags = Tag.all
    @work = Work.find(params[:id])
  end

  def destroy
    @tags = Tag.all
    @work = Work.find(params[:id])
    @work.destroy
    flash[:notice] = "Deleted"
    redirect_to works_index_path
  end

  def show
    @tags = Tag.all

  end

  def index
    @works = Work.all
    @tags = Tag.all
  end

  private
  def work_params
    params.require(:work).permit(:title, :desc, :image, :tag_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/home/index.html.erb
<div class="col-xs-12 col-md-8 col-lg-8">
	<% @works.each do |work| %>
        <div id="work" class="works">
            <%= link_to(image_tag(work.image)) %>
        </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Grapholio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Muli:200" rel="stylesheet">
  </head>

  <body>
		<div class="container">
		    <div class="row">
		    	<%= render 'partials/sidebar' %>
				  <%= yield %>
			</div>

		</div>
  </body>
</html>

app/views/partials/_sidebar.html.erb
<div class="col-xs-12 col-md-4 col-lg-4">
    <div id="brand">
        <%= link_to 'niyazi tanyıldız', root_path %>
    </div>
    <div class="clearfix"></div>
    <div id="sidebar">
        <ul class="category">
        	<% @tags.each do |tag| %>
            	<li><%= link_to tag.name, tags_path(params[:id]) %></li>
            <% end %>
        </ul>
    </div>
</div>

app/views/tags/create.html.erb
<div class="col-xs-12 col-md-8 col-lg-8">

<% if @tag.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@tag.errors.count, "error") %>.
    </div>
    <ul>
    <% @tag.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %> <br />
		<%= text_field_tag @tag.name %>
		<button class='btn btn-default'><%= link_to 'Submit Create', tags_path %></button>
</div>

app/views/tags/destroy.html.erb
<div class="col-xs-12 col-md-8 col-lg-8">
	<%= @tag.name %>
	<%= redirect_to tags_path(tag) %>
</div>

app/views/tags/edit.html.erb
<div class="col-xs-12 col-md-8 col-lg-8">

  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(@tag.errors.count, "error") %>.
      </div>
      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <%= form_for @tag do |tag| %>
  		<%= tag.text_field :name %>
      <%= tag.submit "Update" %>
    <% end %>
</div>

app/views/tags/index.html.erb
<div class="col-xs-12 col-md-8 col-lg-8">


	<table class="table table-striped">
		<thead>
			<tr>
				<th>ID</th>
				<th>Name</th>
				<th>New</th>
				<th>Show</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>
		</thead>
		<tbody>
			<% @tags.each do |tag| %>
			<tr>
				<td><%= tag.id %></td>
				<td><%= tag.name %></td>
				<td><%= link_to 'NEW', new_tag_path %></td>
				<td><%= link_to 'SHOW', tag %></td>
				<td><%= link_to 'EDIT', edit_tag_path(tag) %></td>
				<td><button class="btn button-danger"><%= link_to 'DELETE', tag, method: :delete, data: {confirm: 'Are you sure?'} %></button></td>
				</td>
			</tr>
			<% end %>

		</tbody>
	</table>
</div>

app/views/tags/new.html.erb
<div class="col-xs-12 col-md-8 col-lg-8">


<% if @tag.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@tag.errors.count, "error") %>.
    </div>
    <ul>
    <% @tag.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div style="width:100%">
    <%= form_for @tag do |f| %>
		<%= f.text_field :name %>
		<%= f.submit 'OK', class:'btn btn-success' %>
    <% end %>
</div>
</div>

app/views/tags/show.html.erb
<div class="col-xs-12 col-md-8 col-lg-8">
	<%= @tag.name %> <br />
	<button><%= link_to 'OK', tags_path %></button>
</div>

app/views/tags/update.html.erb
<div class="col-xs-12 col-md-8 col-lg-8">

<% if @tag.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@tag.errors.count, "error") %>.
    </div>
    <ul>
    <% @tag.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


	<% @tag do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %>
	<% end %>
</div>

app/views/works/create.html.erb
<div class="col-xs-12 col-md-8 col-lg-8">


<% if @work.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@work.errors.count, "error") %>.
    </div>
    <ul>
    <% @work.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div style="width:100%">
    <%= form_for @work do |f| %>
    	<%= f.label :title %><br />
		<%= f.text_field :title %><br />

		<%= f.label :image %><br />
		<%= f.text_field :image %><br />

		<%= f.label :description %><br />
		<%= f.text_area :description%><br />

		<%= f.label :tag %><br />
		<%= select("work", "tag_id", Tag.all.collect {|s| [s.name, s.id]}, {include_blank: true})
		<%= f.submit 'OK', class:'btn btn-success' %>
    <% end %>
</div>
</div>

app/views/works/destroy.html.erb
<div class="col-xs-12 col-md-8 col-lg-8">
	<%= @work.name %>
	<%= redirect_to works_path(work) %>
</div>

app/views/works/edit.html.erb
<div class="col-xs-12 col-md-8 col-lg-8">
	<%= form_for @work do |work| %>
        <div id="work" class="works">
        	<%= work.text_field :title %> <br />
        	<%= work.text_area :description %> <br />
        	<%= work.text_field :image %> <br />
            <%= work.submit "Update" %>
        </div>
    <% end %>
</div>

app/views/works/index.html.erb
<div class="col-xs-12 col-md-8 col-lg-8">
	<div style="margin-bottom: 15px;"><%= link_to "Add New", new_work_path, class:"btn btn-primary" %></div>
	<% @works.each do |work| %>
        <div id="work" class="works">
            <%= link_to(image_tag(work.image)) %><br />
            <div>
            <%= link_to "Edit", edit_work_path(work) %>
            <%= link_to "Destroy", work, method: :delete, data: {confirm: 'Are you sure?'} %>
            </div>
        </div>
    <% end %>
</div>

app/views/works/new.html.erb
<div class="col-xs-12 col-md-8 col-lg-8">


<% if @work.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@work.errors.count, "error") %>.
    </div>
    <ul>
    <% @work.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div style="width:100%">
    <%= form_for @work do |f| %>
    	<%= f.label :title %><br />
		<%= f.text_field :title %><br />

		<%= f.label :image %><br />
		<%= f.text_field :image %><br />

		<%= f.label :description %><br />
		<%= f.text_area :description%><br />

		<%= f.label :tag %><br />
		<%= f.collection_select :tag_id, Tag.all, :id, :name, prompt: true %><br />

		<%= f.submit 'OK', class:'btn btn-success' %>
    <% end %>
</div>
</div>

app/views/works/show.html.erb
works#show

app/views/works/update.html.erb
<h1>Works#update</h1>
<p>Find me in app/views/works/update.html.erb</p>